### ISSUE TITLE
阿姆斯特丹

### ISSUE THREAD

**Issue by EsawaAzusa** [PosadasClub/PosadasJournal#1]
《雨水洗不清阿姆斯特丹的罪恶》

因为一些事情，我正好要去阿姆斯特丹一趟。听闻了骇人的事实之后，我希望去现场看一看，碰碰运气，能不能遇到一些当事人。
但是并没有，从下午开始阿姆斯特丹便是小雨。大楼的轮廓在雾气中变得模糊，运河边的街道已经失去了生气，行人的话语也仿佛被这氛围压抑。
当然，这景象中最突兀的还是洒水车——毕竟刚刚下雨，出动洒水车疑似有点自欺欺人了。短短一段路，有三辆洒水车路过，或许这就是眼眶湿润的原因吧。
除了洒水车，和平常不一样的便是警车。四周的路边总是闪着警灯，路边站着的一堆男子像是拿着无线电。
两个一道拐的学生提着一袋饮料走过马路。他们在报考这个学校的时候，有没有想过自己的未来呢？大家纷纷在reddit的荷兰皇家警察学院版块冲锋，然后不知是真不了解还是装不了解的学生嚷嚷着“我们也要工资”，令人不知道该说什么好。
不远处的阿姆斯特丹农业银行的门口有八九个保安站着，他们同样也是拿工资的。
经过现场的时候，威廉一世的画像早已不见踪影，甚至连痕迹都没有。信号屏蔽车也撤走了，大家像往常一样工作生活，仿佛一切没有发声。
我只能尽量的装作一个路人，默默地记住这一切。
沉默的羊群忘记了自己的责任，牧羊犬取代了恶狼。
而运行了两年多的监控手段则让其他沉默者敬而远之。
公园中，纪念碑前的人群让我很意外，走进一看，还是团建。不知道他们听完之后，有什么想法呢。
或许这将是一个平平无奇的日常，或许是一个新时代的开始。

雨水洗不清阿姆斯特丹的罪恶，所以洒水车在街上行驶着。
后记：虽然现在说是逐渐的在还钱了，可能马上就会有人说我这是没事找事破坏大局递刀子，不过你觉得红码都发了人也打了他们一开始是想还钱还是不想还钱？事实证明只有闹才能有收获，要多闹，多和闹，多一闹。
就算真的是在走程序，一个出了事先堵嘴封杀的，公民完全不能了解内部运行只能坐等安排的政府，也是和现代社会所不符的。哪怕是针对长期黑箱操作，闹也是应该的。
————————————————
如果需要照片的话也可以上传

**Comment by PosadasClub** [comment]
方不方便随便上传一张照片？我放在文章里

**Comment by EsawaAzusa** [comment]
> 方不方便随便上传一张照片？我放在文章里
![20220711_175052](https://user-images.githubusercontent.com/54569511/187399935-206b7386-d20a-4dd1-8888-79002717088b.jpg)
这一张中的两个穿制服的是一道杠，意思就是学生

**Comment by PosadasClub** [comment]
好的，谢谢！
