### ISSUE TITLE
我读《共产党宣言》

### ISSUE THREAD

**Issue by Aiwuzhiyang** [PosadasClub/PosadasJournal#5]
我读《共产党宣言》
        我在高中第一次阅读《共产党宣言》时，更多的是为马克思激昂的文笔所倾倒。文本的实际内容似乎是熟悉的不能再熟悉的了。阶级、共产主义这些概念自初中政治历史课本便不断地被填鸭进脑子里。这仅仅是一篇檄文，我这样想。直到我看到了复旦大学张双利教授的宣言导读课，我才清楚，《宣言》远没有看起来易读。作为深刻介入历史进程之中的直至今天依然具有旺盛生命力的宣言，《宣言》背后站着的是马克思深厚的古典哲学基础和恩格斯对国民经济学的钻研。是历史的发展牵动着马克思，他分析现在，把握可能的未来。
工业革命和政治革命后的世界如此绚烂，也如此残酷。行政治解放的资产阶级的确缔造了具有普遍性原则高度的国家，但无产者却堕入了深渊。马克思深感黑格尔的学说难以从天国堕入尘世，在漫长的与黑格尔的“搏斗”后，马克思终于探索出了自己的道路。与恩格斯的相遇为他提供了新的批判武器——对国民经济学的批判。于是市民社会不在模糊不清，分工和私有财产填充了黑格尔的市民社会，也彻底改变了他。马克思战胜了自己曾经的导师，他自己也即将成为新的“导师”。
       七篇序言作为对作为历史性文本的总结，我们应该在梳理完全文四个部分后再谈。引言中：“一个幽灵，共产主义的幽灵，在欧洲游荡。”难道仅仅是一个比喻么？为什们正义者同盟这样一个实际存在的组织会被称之为“幽灵”？的确，面对如此糟糕的生存境遇，工人们，像正义者同盟这样的组织永远都在斗争不是么。这样的“幽灵”将永恒的伴随着资本主义。然而，这样的工人，这样的组织将永远仅仅是工人，仅仅是自发反抗的组织。他达不到明确自身历史使命的无产阶级的自觉的高度，也不能对资本主义制度进行原则性的高度的批判。如果不能做到这些，则“幽灵”将永远不得肉身，就不可能成为对资本主义具有真正威胁性的实体。因此，马克思《共产党宣言》的要义，就在于向工人揭示资本主义和共产主义运动的原则，让“幽灵”成为实体。
        马克思以现代资产阶级入手，提出阶级的概念。绝非先有阶级的概念，然后将这个概念安放到各个历史阶段。马克思从来不是神，社会科学也绝不等同于自然科学。马克思的思想一定从属于他所处在的现代社会，但与一般思想家不同的是马克思可以通过对现代社会的分析把握住内在于这个社会的历史性，他的思想要认真回应经验历史发展的挑战。所以，马克思的学说从来不是什么如地心引力般的自然科学的“铁的规律”。
        在第一章中，马克思分析了资产阶级由一个特殊等级上升为统治阶级的历史进程。他用如此热诚，朝气的散文诗般的语言赞美资本主义的进步性。资本主义的确如此的进步，他是开拓的，是无穷变化的，华丽的商品堆积如山，一切稳固的都烟消云散了。他冲破了血缘，他毁灭了神圣，他去除了政治特权！这是一个全新的社会，阶级统治在这里落实为经济统治。形式上的平等和民主激荡着整个欧洲。这不愧为对资本主义最佳的赞美。
上升到统治阶级的资产阶级改变了世界。他首先将这个社会不断地商品化，正如《宣言》中所言：“它无情地斩断了把人们束缚于天然尊长的形形色色的封建羁绊，它使人和人之间除了赤裸裸的利害关系，除了冷酷无情的“现金交易”，就再也没有任何别的联系了。” 人，自由了，虽然是处在商品关系中买与卖的原子化的自由，但人依然冲破了封建束缚。当然资本主义还在不断合理化自身，新的教育模式和大工厂构建了新的伦理和生活方式。封建社会的“旧人”将被变为顺从资本主义的“新人”。
       生产力的狂飙突进带来的不光是进步，还有人的匮乏。资本与技术合谋下，工人劳动的内容愈加抽象，也愈加不属于自己，只变成那异己的敌对的力量。人首先不是作为人，而是作为工人而活，因为不作为工人就无法维持作为人的生命。同时，资本主义开始扫除一切与他不相容的事物，并不断强化自身的力量。用商品和技术横扫欧洲的资本主义没有一丝疲劳地奔向整个世界，开拓是他的宿命，他一刻也不能停歇。否则，生产过剩的危机便会将他击得粉碎。
        危机，自信满满的开拓者们的噩梦，资本主义结构性的不可能克服的缺陷。资产阶级“现在像一个魔法师一样不能再支配自己用法术呼唤出来的魔鬼了。”膨胀的生产力不受资产阶级自身的控制，资产阶级自身面对资本的“魔力”也无能为力。无比强大的生产力没有造福社会，他的造物并不能作为资源回馈社会，工人受到如此残酷的剥削以至于除了维持生存他们难以进行其他消费了。于是，前所未有的生产过剩性质的危机开始了。马克思告诉我们，封建社会之所以能迈入资本主义社会，是因为生产力超出了封建生产关系，并对其进行破坏，而后新的生产方式萌生吞噬了旧的生产关系。而资本主义的社会矛盾的与封建社会的根本差异在于，带来生产过剩的危机的生产力并不会创造新的生产关系，生产过剩危机的结果是对生产力的单纯破坏，随之而来的是大规模失业，即大量的工人被抛出资本主义生产体系。度过危机的方法不过是对资本主义发展逻辑的简单重复，即开拓市场，创造新需求。所以资本主义的灭亡必定不会像封建社会灭亡那样先在经济上发生生产关系的变革，后发生推翻封建王朝的政治革命；而是恰恰相反，资本主义的灭亡必定以无产阶级的夺取资产阶级国家的政治革命为先导。生产力作为资产阶级曾经的盟友，现在将化作利刃由上升为无产阶级的工人作为主体使用，刺穿资本主义的心脏。
        工人之为工人，首要在于其被资本主义规定，被嵌在商品化关系之中。在劳动力市场的永无止境的竞争中，是工人与工人之间彻底的关系的切断，工人们在市场之中的自我竞争是“所有人反对所有人”的战争。大量的过剩人口即失业群体是这场战争的保障。而在资本主义合理化的过程中，劳动内容的愈加抽象使工人彻底被规定。我们通常所言的无产阶级的具有的“纪律性”与其说属于其自身，不如说是整个体系的外在强加。但工人们毕竟不是机器，他们会反抗。面对日益抽象，丧失自我规定性的强迫的劳动，刚从中世纪行会师傅转变为雇佣工人的无产者们开始了反对生产工具——机器——的运动。随后工人们开始参加争夺普遍性权利的政治斗争中去。只有在不断地反抗中，工人才能不只是工人，他才能上升为那个自觉的，清晰自己历史使命的无产阶级。这就像是黑格尔所讲，市民通过现实伦理机制上升到自觉认同作为普遍性原则的国家一样。为了使工人的上升不至于成为空想，马克思指出了教育组织工人的三重因素。列宁讲：“文盲没有资格参与政治。”工人首先要通过政治斗争，明白现代资产阶级权利，成为“公民”。“资产阶级自己就把自己的教育因素即反对自身的武器给予了无产阶级”，正因为资产阶级宣称他们所争取的权利是普遍的，是反对封建特权的，工人们才能有理由去争取，也才会发现资产阶级的承诺是如此的空洞，那种自称普遍的权利根本不能落实。随后马克思则强调在资本主义日益发展，危机的不断重演会让大量资本家破产，坠入被统治阶级中。他们将向无产者揭露资本主义的秘密。而最重要的，是像马克思恩格斯一样，“已经提高到从理论上认识整个历史运动这一水平的一部分资产阶级思想家，转到无产阶级方面来了”的资产阶级知识分子。本雅明使用“改宗”一词形容他们再贴切形象不过了。他们将彻底超越资产阶级的狭隘偏见，带领被组织成为阶级的无产者迈向自由王国。那时，资本主义自称代表和践行的“自由”，将不再被私有财产这一机制所阻碍，历史的下一环节将实现上一环节的真理。
       在第一章的最后，马克思简明地介绍了社会中其他各阶级的情况，他们或保守，或反动。而“无产阶级的运动是绝大多数人的、为绝大多数人谋利益的独立的运动”，工人的解放从来就是对资本主义所有人的解放！
       在第二章《无产者和共产党人》，马克思指明了共产主义原则，又对眼前的资本主义社会进行了批判。马克思告诉我们，作为代表无产阶级的政党的共产党，他一定是把握住无产阶级革命原则的，而这个原则一定是内在于无产阶级革命的事实的运动之中的。而这个革命的原则，就是对现存状况的否定，即“消灭私有制”。消灭私有制，意味着对人与人间阶级统治关系的实质消灭。随后，马克思展开了与自由主义的经典论战，为自己的观点辩护。黑格尔宣称：“私有财产是人自由意识的定在”。马克思并没有急着否定黑格尔，而是先肯定了黑格尔的观点。的确，在资本主义社会下发展到极致的私有财产的确带来了形式上的普遍自由。在买卖关系中，人的确是自由的，买方与卖方也必然是平等的，否则就不再是买卖关系了。但除此之外，私有财产的落实恰恰是对自由概念的自我否定，它带来的只有统治。这样的社会能够带来自由个性的自我张扬么？不会，他只会带来彻底臣服于私有财产规定的同质化。为什么经由社会化生产积累起来的资本却成为了个别资本家的私有物？作为劳动主体的工人的所谓“劳动收入”——工资——为何和工人的劳动毫不相干。资本源于社会性质的一般劳动，却被掌管在私人手中，自由劳动带来的是少数人的富裕，却不曾造福真正劳动的人。事实上，资本作为排它的力量支配着每个人，掌握着整个世界。进一步来讲，私有财产也从不局限于黑格尔所言的“市民社会”，他也是家庭、国家的规定性力量！马克思用一种彻底的、毫不留情的语言讥讽资产阶级的伪善，无产阶级必须与旧社会旧原则的彻底决裂！与私有财产原则决裂！与支撑人们对私有财产关系信仰的意识形态决裂！
       无产阶级的政治革命在先，社会革命在后的观点再次被马克思重申：“工人革命的第一步就是使无产阶级上升为统治阶级，争得民主。无产阶级将利用自己的政治统治，一步一步地夺取资产阶级的全部资本，把一切生产工具集中在国家即组织成为统治阶级的无产阶级手里，并且尽可能快地增加生产力的总量。”在这里我们也能看出，马克思不是对黑格尔“国家是市民社会的根据”的简单颠倒。事实上，马克思向后退了一步，正是生产力的发展让资本主义生产关系能够冲破封建关系的束缚，使资产阶级首先成为了封建国家的一个特殊的等级。而后通过法国大革命这样的政治革命，资产阶级夺取国家政权并上升为统治阶级。只有掌握了国家，资产阶级才能彻底的控制这个社会，贯彻资产阶级的意志，扫除旧的腐朽的生产关系，将资本主义生产关系在全国推行。国家的确如黑格尔所言，是维护这个资本主义社会的重要因素，没有这样的国家，资本主义社会也行将崩塌。而资本主义下生产力的发展不能带来新的社会关系。这样的话，无产阶级只有先进行政治革命夺取并改造整个资产阶级国家机器，才能贯彻自身阶级的意志，进而按照阶级利益改造整个社会。马克思恩格斯从不否认上层建筑能够起决定性的作用。
       在第二章的结尾，马克思为无产阶级的革命提出了十条建议。前四条的目的是限制私有财产；5-7条在新社会如何安排社会生产；8-7条告诉我们不再作为私有财产生产的社会资源如何真正的回馈社会。这十条建议有的或许今日已经不再适用，但我们可以看出马克思是现实的。他没有激进到一下子废除继承权的地步。他承认新社会首要是恢复和保持既定的生产，只有经济能够在革命的无产阶级国家中运行下去，社会革命才能有保障。“每个人的自由发展是一切人的自由发展的条件”的社会才能落地。
       第三章《社会主义的和共产主义的文献》是对当时各种流行的关于社会主义思潮的批判。1888年英文版序言中，恩格斯（马克思于1883年去世）告诉我们，正因为当时“社会主义”的名号被空想主义者和“庸医”占据着，而“只有工人阶级中确信单纯政治变革还不够而公开表明必须根本改造全部社会的那一部分人，只有他们当时把自己叫做共产主义者。”马恩因此才会选用“共产主义”作为宣言的旗帜。
       马克思罗列了三种反动的“社会主义”：封建的、小资产阶级的、德国小市民的。作为曾经的统治阶级，旧贵族们对资本主义社会是矛盾的，虽然他们中的大多数在这个社会中同样发了横财，但终归丧失了旧有的特权，于是他们也走上前台，假惺惺地为无产者高呼正义了。小资产阶级的社会主义“非常透彻地分析了现代生产关系中的矛盾。它揭穿了经济学家的虚伪的粉饰。它确凿地证明了机器和分工的破坏作用、资本和地产的积聚、生产过剩、危机、小资产者和小农的必然没落、无产阶级的贫困、生产的无政府状态、财富分配的极不平均、各民族之间的毁灭性的工业战争，以及旧风尚、旧家庭关系和旧民族性的解体。”他在理论上达到了一定的高度，可结果却是要求倒退回他们幻想中的“田园牧歌”中去。马克思对德国小市民的社会主义的分析最为出彩。德国小市民的社会主义思潮是从法国传来的，而这种在法国充满斗争性的学问却被德国的哲学家们阉割了。在德国“哲学家、半哲学家和美文学家，贪婪地抓住了这种文献，不过他们忘记了：在这种著作从法国搬到德国的时候，法国的生活条件却没有同时搬过去。在德国的条件下，法国的文献完全失去了直接实践的意义，而只具有纯粹文献的形式。它必然表现为关于真正的社会、关于实现人的本质的无谓思辨。”而这种超越了德国现状的学说被统治者所欣赏，他们用这种社会主义思想来迫害当时德国的自由主义运动，迫害参与革命的劳工。这种小市民的社会主义在今天也非常的受到某些人的欢迎，他们挥舞起某种不切实际，仅仅是被高高举起的原则——无害的神像——指责受困于泥潭的工人运动。资本主义的社会主义无非是通俗的改良主义，不多赘述。而对空想社会主义，马克思认为他们是想实现“上帝般从无到有的创造”。空想社会主义在真正的阶级斗争出现前诞生，他们看到了资本主义的弊病，但却只能依靠小规模的实验，依靠有良心的资产者。当真正的工人运动出现时，他们被吓坏了，走向反动。“批判的空想的社会主义和共产主义的意义，是同历史的发展成反比的”，马克思公允的评价道。
       第四章《共产党人对各种反对党派的态度》是在一般原则意义论述无产阶级革命同每一个在具体处境中展开的性质不同的革命之间的关系。虽然短小，但却极其重要。通常，我们一提到无产阶级革命，一定要强调他的条件：1.生产力高度发展2.无产者作为一个阶级被组织起来。而马克思在文本中告诉我们的是，只要工人已经开始成为实际发生着的革命运动的主体，无产阶级革命就已将开始展开！《宣言》发表后不久爆发的1848大革命，虽然争取的是资产阶级的权利，但参与革命主体确是实实在在的无产者。马克思认为，如果没有外力阻隔，保持对消灭私有制原则的坚守，这样的革命就一定能发展到无产阶级革命的高度。中国的新民民主主义革命虽然同样是履行资产阶级的历史使命，但主体却是农民，并在共产党的领导下，实现了社会主义的事业。马克思列举了面对欧洲各国波谲云诡的政治形势，共产党应该怎么做。“共产党人为工人阶级的最近的目的和利益而斗争，但是他们在当前的运动中同时代表运动的未来”，共产党无论在何种处境中，一定实实在在地介入和支持反对现存秩序的代表无产阶级利益的任何斗争。但同时，他们必然要有对运动本身的原则高度的超越，“在所有这些运动中，他们都特别强调所有制问题是运动的基本问题，不管这个问题的发展程度怎样。”无产阶级的斗争从来不需要“等待戈多”式的荒谬的生产力的“解放”，有压迫，就有反抗，斗争的“幽灵”永不停歇。无产阶级革命不被一种模式束缚，他是开放的，向时代敞开的。
       让我们倒过头来回到七篇序言。七篇序言交待了文本写作的缘起，恩格斯对文本的核心内容进行了概括。同时序言还厘清了文本与国际工人运动的关系，梳理了文本的不同版本。我们从序言中可以看出，马克思在斗争时是怎样坚守原则性和灵活性的。在第一国际建立，工人运动从1848革命失败刚刚走出时，他向拉萨尔派和蒲鲁东派的妥协。他老年时对俄国公社的不断探索。序言中指出，我们不能简单地利用资产阶级旧的国家机器，这无疑是对《宣言》的反思。而资本主义在19世纪末的变革也让《宣言》饱受挑战。马克思和恩格斯在晚年摆脱了历史目的论和欧洲中心论，他们又有了全新的视野。而新的人类学研究让马恩意识到资本主义的起源原比自己想象的复杂。我们也绝不能误读恩格斯“在我看来这一思想对历史学必定会起到像达尔文学说对生物学所起的那样的作用”这句话。社会科学绝不是自然科学，恩格斯认为马克思的历史唯物主义对于当时社会科学的研究起到了像达尔文那样“开天辟地”的作用，但绝不意味着马克思的思想像达尔文的进化论那样是实证的科学，这是将马克思的学说倒退回机械唯物主义和形而上学。
       因此，无产阶级的必然胜利是马克思针对1848年的现实而分析把握的一种可能，绝不是什么“自然规律”。阶级斗争的结果从来也不是单向的，同归于尽，还是迈向未来，一切都是未知的，是敞开的。那么，没有所谓必然性保证的无产阶级运动难道就会失去什么么？永远不会。只要经济危机还在，只要对自我竞争厌倦了的无产者还在，只要过剩人口还在，只要马克思恩格斯这样的有机知识分子还在，斗争就依然存在！
    死亡不属于无产阶级！全世界无产者联合起来！

**Comment by EsawaAzusa** [comment]
“文盲没有资格参与政治。”列宁这句话原意应该是“文盲被排除在政治之外。”

**Comment by Aiwuzhiyang** [comment]
我平常不怎么看邮箱，回的太晚了😵。
我好像在引用这句话的时候有点“等级制”的意味。请问您对那篇文章有什么具体修改的点子么😘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月2日(周五) 晚上6:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PosadasClub/PosadasJournal] 我读《共产党宣言》 (Issue #5)




 
“文盲没有资格参与政治。”列宁这句话原意应该是“文盲被排除在政治之外。”
